baseURL = "https://rahasia.ahmadiham.id/"
title = "Psssttt... jangan dibuka..."
author = "root"
copyright = "Copyright © 2020, Root; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

ignoreErrors = ["error-remote-getjson"]
  
theme="root"

#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"
